// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJMw8TazJ4JSDqHtaN335AQuDYF2sUzwc',
    appId: '1:864510601792:web:97ecdfe80c8b40b1d3cda5',
    messagingSenderId: '864510601792',
    projectId: 'license-plate-detector-1b4ea',
    authDomain: 'license-plate-detector-1b4ea.firebaseapp.com',
    storageBucket: 'license-plate-detector-1b4ea.appspot.com',
    measurementId: 'G-T8TZTZXRTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ1zfWayHJdR8A0aCsxqqXKgqphh8uIEY',
    appId: '1:864510601792:android:6d7fea3fa535d44ed3cda5',
    messagingSenderId: '864510601792',
    projectId: 'license-plate-detector-1b4ea',
    storageBucket: 'license-plate-detector-1b4ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOywhsYmcX7tckqAlD5xXgcQ_d3O4ln7A',
    appId: '1:864510601792:ios:cf179c7318d4a641d3cda5',
    messagingSenderId: '864510601792',
    projectId: 'license-plate-detector-1b4ea',
    storageBucket: 'license-plate-detector-1b4ea.appspot.com',
    iosClientId: '864510601792-5jtv449ou8sdi5d7u8amnhflqkd62v6e.apps.googleusercontent.com',
    iosBundleId: 'com.example.licenseplatedetector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOywhsYmcX7tckqAlD5xXgcQ_d3O4ln7A',
    appId: '1:864510601792:ios:cf179c7318d4a641d3cda5',
    messagingSenderId: '864510601792',
    projectId: 'license-plate-detector-1b4ea',
    storageBucket: 'license-plate-detector-1b4ea.appspot.com',
    iosClientId: '864510601792-5jtv449ou8sdi5d7u8amnhflqkd62v6e.apps.googleusercontent.com',
    iosBundleId: 'com.example.licenseplatedetector',
  );
}
